[project]
name = "runia"
version = "2.0.0"
description = "Runtime Uncertainty estimation for AI models"
readme = "README.md"
requires-python = ">=3.9"
authors = [
  {name = "Fabio Arnez", email = "fabio.arnez@cea.fr"},
  {name = "Daniel Montoya", email = "daniel-alfonso.montoyavasquez@cea.fr"}
]
dependencies = [
    "black>=24.8.0",
    "dropblock>=0.3.0",
    "entropy-estimators>=0.0.1",
    "faiss-gpu>=1.7.2",
    "hydra-core>=1.3.2",
    "matplotlib>=3.8.4",
    "mlflow>=2.6.0",
    "numpy>=1.26.4",
    "opencv-python>=4.10.0.84",
    "packaging>=23.2",
    "pacmap>=0.7.0",
    "pandas>=2.2.0",
    "torch>=2.1.0",
    "pytorch-lightning>=2.2.0",
    "scikit-image>=0.24.0",
    "scikit-learn>=1.6.1",
    "scipy>=1.13.1",
    "seaborn>=0.13.2",
    "tensorboard>=2.17.0",
    "torchvision>=0.16.0",
    "torchaudio>=2.1.0",
    "torchmetrics>=1.8.2",
    "tqdm>=4.67.1",
]

[tool.black]
line-length = 100
target-version = ['py39']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''